config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  resources :categories do
    resources :tasks
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  root to: "home#index"
  
  post '/categories' => 'categories#create', as: 'create_category'
  post '/categories/:category_id/tasks' => 'tasks#create', as: 'create_task'

  delete '/categories/:category_id/tasks/:id' => 'tasks#destroy', as: 'delete_task'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    validates :name, presence: true, uniqueness: true
    validates :due_date, presence: true  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :get_category


    def index
    end

    def new
        @task = Task.new
    end

    def show
        @task = Task.find(params[:id])
    end

    def edit
        @task = Task.find(params[:id])
    end

    def create
        @task = @category.tasks.build(task_params)

        if @task.save
            redirect_to categories_path, notice: 'Task successfully created!'
        else
            render :new
        end

    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to categories_path, notice: 'Task successfully updated!'
        else
            render :edit
        end
    end

    def destroy
        @task = Task.find(params[:id])
        if @task.delete
            redirect_to categories_path, notice: 'Task successfully removed!'
        else
            render :edit
        end
    end

    private
    def get_category
        @category = Category.find(params[:category_id])
    end

    def task_params
        params.require(:task).permit(:name, :due_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="h-screen bg-green-200 flex items-center justify-center p-5 w-screen">
    <div class="w-1/2 p-2">
        <%= form_with model: [@category, @task] do |f| %>    
            <div class="field font-bold text-2xl">
                <label>📝 Modifying task:</label><br /><br />
                <%= f.text_field :name, autocomplete: :off, class: 'mb-4 text-base text-black p-2 rounded w-full', placeholder: 'enter name' %>
                <%= f.date_field :due_date, class: 'text-base p-2 w-full' %>
            </div>
            <% if @task.errors.any? %>
                        <ul classs="validation-message">
                            <% @task.errors.full_messages.each do |message| %>
                                <li style="list-style-type:none; color:#ff2e46;"><%= message.downcase %></li>
                            <% end %>
                        </ul>
                <% end %><br />

            <dic class="actions flex justify-center gap-10">
                <%= f.submit '✔ Submit', data: {confirm: 'Are you sure?'}, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white'%>
                
                <%= link_to '👈 back', category_path(@category.id), class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="h-screen bg-green-200 flex items-center justify-center p-5 w-screen">
    <div class="w-1/2 p-2">
        <%= form_with model: [@category, @task], url: create_task_path do |f| %>
        
            <div class="field font-bold text-2xl">
                <label>📝 Task name:</label><br /><br />
                <%= f.text_field :name, autocomplete: :off, class: 'mb-4 text-base text-black p-2 rounded w-full', placeholder: 'enter name' %>
                <%= f.date_field :due_date, class: 'text-base p-2 w-full' %>
            </div>
                <% if @task.errors.any? %>
                        <ul classs="validation-message">
                            <% @task.errors.full_messages.each do |message| %>
                                <li style="list-style-type:none; color:#ff2e46;"><%= message.downcase %></li>
                            <% end %>
                        </ul>
            <% end %><br />


            <div class="actions flex justify-center gap-10">
                <%= f.submit '✔ Submit', data: {confirm: 'Are you sure?'}, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white'%>
                
                <%= link_to '👈 categories', categories_path, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="h-screen flex items-center justify-center p-5 w-screen">
            
    <div class="flex flex-col gap-5">
        <div class="max-w-sm rounded overflow-hidden shadow-lg">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2"><%= @task.name.upcase %></div>
                <p class="text-gray-700 text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
                </p>
            </div>
        </div>
        <div class="flex justify-center">
            <%= link_to '👈 back', category_path(@category.id), class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
        </div>
    
    </div>

</div>