config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  resources :categories do
    resources :tasks
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  root to: "home#index"
  
  post '/categories' => 'categories#create', as: 'create_category'
  post '/categories/:category_id/tasks' => 'tasks#create', as: 'create_task'

  delete '/categories/:category_id/tasks/:id' => 'tasks#destroy', as: 'delete_task'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
      @id = current_user.id
      @tasklist = Task.find_by_sql(
        " select categories.name as category_name, tasks.name as task, tasks.due_date as due
        from tasks left join categories on categories.id = tasks.category_id
        left join users on users.id = categories.user_id
        where categories.user_id = #{@id}
        order by categories.id
      ")
      
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="h-screen">
    <div class="header h-1/4">
        <div class="flex flex-row justify-around pt-5">
            <span style="font-size:30px;cursor:pointer" class="mobile-nav hidden md:block">
                <!--&#9776; open -->
                    &#9776;
            </span>
            
            <div>
                <h1 class="font-bold text-2xl md:hidden">👤Hi, <span class="capitalize"><%= "#{current_user.username}!"%></span>
            </div>
                <!-- Mobile nav links start -->
                <div id="navs" class="overlay">
                    <a href="javascript:void(0)" class="closebtn">&times;</a>
                    <div class="navs-content">
                        <%= link_to  '📑 Categories', categories_path, class: 'nav-categories' %>&nbsp;<span>|</span>&nbsp;
                        <%= link_to  '📴 Sign out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}, id: "out", class: 'nav-out' %>
                    </div>
                </div>
                <!-- Mobile nav links end -->

            <div class="font-bold md:hidden">
                📑<%= link_to  'Categories', categories_path %>&nbsp;<span>|</span>&nbsp;
                📴<%= link_to 'Sign out',destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}, id: "out"  %>
            </div>
        </div>
            <br /><hr /><br />

        <div class="flex justify-center bg-green-400 w-full">
            <p class="notice text-center text-2xl p-2 font-bold"><%= notice %></p>
        </div><br /><br />
    </div>

    <div class="section h-3/4 flex flex-col">
            <div class="greetings flex justify-around md:justify-center md:flex-col md:items-center">
    
                <div class="rounded-xl p-2 w-2/5 md:w-4/5 md:mt-5">
                    <h1 class="pb-3 pl-2 text-base">
                        <span class="font-bold text-2xl">Todo today : </span>
                        <span class="italic">(<%= Date.today.strftime('%a %d %b %Y') %>)</span>
                    </h1>
                    <hr class="class border-black"></hr>
                    <ul>
                        <% @tasklist.each do |t| %>
                            <%if t.due. <= Date.today %>    
                            <div class="rounded p-1 indent-1">
                                <div class="inline-flex items-center leading-none text-purple-600 rounded-full p-2 shadow text-teal text-sm">
                                    <span class="inline-flex bg-indigo-600 text-lg text-white rounded-full h-6 p-3 justify-center items-center">
                                        <%= t.category_name%>
                                    </span>
                                    <span class="inline-flex px-2 text-base font-bold">
                                        <%= t.task%>
                                    </span>
                                </div>
                            </div>
                            <% end %>
                        <% end %>
                    </ul>                     
                </div>
                <div class="w-fit md:ml-20">
                    <%= image_tag 'welcome.jpg', alt: 'welcome image' %>
                    <h1 class="font-bold text-2xl">✋ Hello There,</h1><br />
                    <p class="indent-2">You may now start building your daily accomplishments.</p>
                    <p>organize it by category.</p> <br />

                </div>
            </div><br />
            <div class="flex flex-col items-center">
                <%= image_tag 'landing.jpg', alt: 'welcome image', :style => 'width: 400px' %>
                <h1 class="font-bold text-2xl italic md:text-center">👏 Welcome, You can to start using Today.</h1><br />
            </div>
    </div>

</div>