config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  resources :categories do
    resources :tasks
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  root to: "home#index"
  
  post '/categories' => 'categories#create', as: 'create_category'
  post '/categories/:category_id/tasks' => 'tasks#create', as: 'create_task'

  delete '/categories/:category_id/tasks/:id' => 'tasks#destroy', as: 'delete_task'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    
    validates :name, presence: true, uniqueness: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @categories = current_user.categories
    end

    def new
        @category = current_user.categories.build
    end

    def show
        @category = current_user.categories.find(params[:id])
    end

    def edit
        @category = current_user.categories.find(params[:id])
    end

    def create
        @category = current_user.categories.build(category_params)
        
        if @category.save
            redirect_to categories_path, notice: 'Category successfully created!'
        else
            render :new
        end

    end

    def update
        @category = current_user.categories.find(params[:id])
        if @category.update(category_params)
            redirect_to categories_path, notice: 'Category successfully updated!'
        else
            render :edit
        end
    end


    private
    
    def category_params
        params.require(:category).permit(:name)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="w-1/2 p-2">

    <%= form_for @category, url: create_category_path do |f| %>
        
            <div class="field font-bold text-xl">
                <label>📝 Category name:</label><br /><br />
                <%= f.text_field :name, autocomplete: :off, class: 'w-full text-base text-black p-3 rounded', placeholder: 'enter name', id: 'name' %>
            </div>
            <% if @category.errors.any? %>
                        <ul classs="validation-message">
                            <% @category.errors.full_messages.each do |message| %>
                                <li style="list-style-type:none; color:#ff2e46;"><%= message.downcase %></li>
                            <% end %>
                        </ul>
            <% end %><br />
            <div class="actions flex justify-center gap-10">
                <%= f.submit '✔ Submit', data: {confirm: 'Are you sure?'}, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white', id: 'submit'%>
                
                <%= link_to '👈 categories', categories_path, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
            </div>
        
    <% end %>

</div>

app/views/categories/_main.html.erb
   <div class="flex flex-row justify-around pt-5">
            <span style="font-size:30px;cursor:pointer" class="mobile-nav hidden md:block">
                <!--&#9776; open -->
                    &#9776;
            </span>
            
            <div>
                <h1 class="font-bold text-2xl md:hidden">👤Welcome, <span class="capitalize"><%= "#{current_user.username}!"%></span>
            </div>
                <!-- Mobile nav links start -->
                <div id="navs" class="overlay">
                    <a href="javascript:void(0)" class="closebtn">&times;</a>
                    <div class="navs-content">
                        <%= link_to  '➕ Categories', new_category_path, class: 'nav-categories' %>&nbsp;<span>|</span>&nbsp;
                        <%= link_to  '🔙 Back', root_path, class: 'nav-back' %>&nbsp;<span>|</span>&nbsp;
                        <%= link_to  '📴 Sign out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'nav-out' %>
                    </div>
                </div>
                <!-- Mobile nav links end -->

            <div class="font-bold md:hidden">
                ➕ <%= link_to  'Categories', new_category_path %>&nbsp;<span>|</span>&nbsp;
                🔙<%= link_to  'Back', root_path %>&nbsp;<span>|</span>&nbsp;
                📴 <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'} %>
            </div>
        </div>
            <br /><hr /><br />

        <div class="flex justify-center bg-green-400 w-full">
            <p class="notice text-center text-2xl p-2 font-bold"><%= notice %></p>
        </div>



<!-- 
<div class="flex flex-row justify-around pt-5">
    <div>
        <h1 class="font-bold text-2xl">👤Hi, <%= current_user.email%></h1>
    </div>
        <div class="font-bold">
        ➕ <%= link_to  'Categories', new_category_path %>&nbsp;<span>|</span>&nbsp;
        🔙<%= link_to  'Back', root_path %>&nbsp;<span>|</span>&nbsp;
        📴 <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
</div>
        <br /><hr /><br />

    <div class="flex justify-center bg-green-400 w-full">
        <p class="notice text-center text-2xl p-2 font-bold"><%= notice %></p>
    </div>


-->

app/views/categories/edit.html.erb
<div class="h-screen bg-green-200 flex items-center justify-center p-5 w-screen">

    <div class="w-1/2 p-2">
    <%= form_for @category do |f| %>
            <div class="field font-bold text-xl">
                <label>📝 Modifying category:</label><br /><br />
                <%= f.text_field :name, autocomplete: :off, class: 'w-full text-base text-black p-3 rounded', placeholder: 'enter name' %>
            </div>
            <% if @category.errors.any? %>
                        <ul classs="validation-message">
                            <% @category.errors.full_messages.each do |message| %>
                                <li style="list-style-type:none; color:#ff2e46;"><%= message.downcase %></li>
                            <% end %>
                        </ul>
            <% end %><br />

            <div class="actions flex justify-center gap-10">
                <%= f.submit '✔ Submit', data: {confirm: 'Are you sure?'}, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white'%>
                
                <%= link_to '👈 categories', categories_path, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
            </div>
    <% end %>
    </div>
</div>
    

app/views/categories/index.html.erb
<%= render 'main'%>
<br /></br /><br />


    <ul class="grid justify-center gap-2 grid-cols-4 sm:grid-cols-1 md:grid-cols-2 p-2">
    <% @categories.each do |category|%>
    <% @count = Task.where("category_id = ?", category.id).count%>
        
            <li>
                <div class="max-w-sm rounded overflow-hidden shadow-lg bg-green-200">
                    <div class="px-6 py-4">
                        <div class="font-bold text-2xl mb-2 capitalize"><%= category.name %></div>
                        
                        <div class="indent-1 text-xs"><span class="font-bold"> Date created: </span><%= category.created_at.strftime('%a %d %b %Y')%><!--&nbsp; <%= category.created_at.strftime("at %I:%M%p")%>--></div>
                        <div class="indent-1 text-xs"><span class="font-bold"> Last modified: </span><%= category.updated_at.strftime('%a %d %b %Y')%><!--&nbsp; <%= category.updated_at.strftime("at %I:%M%p")%>--></div>
                        <br />
                        <p>task count : <span class="font-bold"><%= @count%></span></p>
                        
                    </div>
                    <div class="flex justify-center gap-5">
                        <%= link_to '👓view', category_path(category.id), class: 'bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2' %>
                        <%= link_to '⚙ edit', edit_category_path(category.id), class: 'bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2' %>
                    </div>
                </div><br />
                <div class="flex justify-center">
                <%= link_to '➕ task', new_category_task_path(category.id), class: 'text-center w-full bg-gray-200 rounded px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2' %>
                </div>
            </li>
    <% end %>
    </ul>
    

app/views/categories/new.html.erb
<div class="h-screen bg-green-200 flex items-center justify-center p-5">
    <%= render 'form', category: @category%>
</div>
    

app/views/categories/show.html.erb
<div class="h-screen flex items-center justify-center p-5 w-screen">

<div class="flex flex-col gap-5">
        <div class="max-w-full rounded overflow-hidden shadow-lg">
                <div class="px-6 py-4">
                        <div class="font-bold text-3xl mb-2 text-center"><%= @category.name%></div>
                        <p class="text-gray-700 text-base">
                        <% @tasks = Task.where("category_id = ?", @category.id) %>
                                <table>
                                <thead>
                                        <tr>
                                        <td class="text-center text-base font-bold">Tasks</td>
                                        <td class="text-center text-base font-bold">Due date</td>
                                        <td colspan="3"></td>
                                        </tr>
                                </thead>
                                <tbody>
                                <% @tasks.each do |task| %>
                                        <tr>
                                        <td class="text-base p-3 font-bold capitalize"><%= task.name%></td>
                                        <td class="p-3 text-sm"><%= task.due_date.strftime('%a %d %b %Y')%></td>
                                        <td>
                                                <%= link_to '👓', category_task_path(@category.id, task.id), class: 'inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2'%>
                                        </td>
                                        <td>
                                                <%= link_to '⚙', edit_category_task_path(@category.id, task.id), class: 'inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2'%>
                                        </td>
                                        <td>
                                                <%= link_to '❌', delete_task_path(@category.id, task.id), class: 'inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2', data: {confirm: 'Are you sure?'}, method: :delete %>
                                        </td>
                                        </tr>
                                <% end %>
                                </tbody>       
                                </table>
                                        
                        </p>    
                        </div>
                </div>
                <div class="flex justify-center gap-5">
                <%= link_to '➕task', new_category_task_path(@category.id), class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
                <%= link_to '👈 categories', categories_path, class: 'bg-green-700 p-2 rounded text-white hover:bg-red-700 text-white' %>
                </div>
        </div>
</div>